services:
  - type: web
    name: epa-facilities-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_DUMP_URI
        sync: false
    healthCheckPath: /health

